# To run use:
# rustup toolchain install nightly
# rustup component add rustfmt --toolchain nightly
# cargo +nightly fmt

max_width = 120
format_strings = true
normalize_comments = true
imports_granularity = "Crate"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 100
trailing_comma = "Never"
wrap_comments = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
unstable_features = true
style_edition = "2024"
comment_width = 100
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"