[package]
name = "workflow"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "workflow"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
tera = "1.20"
dialoguer = "0.12.0"
indicatif = "0.18.0"
crossterm = "0.29.0"
directories = "6.0.0"
