---
name: Get Current Kubernetes Deployments
command: "kubectl get deployments -n {{namespace}} -o name"
description: Workflow to get the current Kubernetes deployments
arguments:
  - name: namespace
    arg_type: Enum
    enum_name: namespaces
    enum_command: "kubectl get namespaces | awk 'NR>1 {print $1}'"
    description: Namespace to apply scale to
    default_value: ~
tags: []
source_url: ~
author: ~
author_url: ~
shells: []
